### ISSUE TITLE
Feedback by nizil shah

### ISSUE THREAD

**Issue by nokibsarkar** [nokibsarkar/bot-wikifolklore#161]
Few things i noticed:

- [x]  there are no links to titles (articles).. I  prefer to check out quality of the article before i start translation.. so a link should be there which opens in new tab
- [ ] #162

**Comment by wasiulbahar** [comment]
More from Nizil
3. I tried on mobile.. so when content translation link is clicked and "translate" pressed it leads to just translation tool but not original/target articles appear.. just tool is opened.. may be issue on mobile only
